
 export const  GET_REQUEST="GET_REQUEST";
 export const  GET_SUCCESS="GET_SUCCESS";
 export const  GET_FAILURE="GET_FAILURE";

 export const USER_PATCH_REQUEST="USER_PATCH_REQUEST";
 export const USER_PATCH_SUCCESS="USER_PATCH_SUCCESS";
 export const USER_PATCH_FAILURE="USER_PATCH_FAILURE";
